title: Runtime
description: The Runtime Working Group is responsible for AMP's core runtime, such as layout/rendering and data binding.
facilitator:
  login: jridgewell
  name: Justin Ridgewell
members:
  - login: jridgewell
    name: Justin Ridgewell
  - login: choumx
    name: William Chou
